name: dl_py312
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip
  - pip:
      - datasets
      - gensim
      - huggingface-hub
      - ipykernel
      - ipython==9.5.0
      - matplotlib
      - matplotlib-inline
      - nltk==3.9.2
      - numpy==1.26.4
      - opencv-python
      - pandas==2.3.2
      - pillow==11.3.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - scikit-learn==1.7.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.56.2
      - triton==3.4.0
      - urllib3==2.5.0